### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by Wicpar** [storj-thirdparty/uplink-rust#60]
Hi,
I'm trying to use this crate in a windows environment, however the build fails due to the missing commands like "cp"

**Comment by ifraixedes** [comment]
Hi @Wicpar.

It's expected, the `uplink-sys` crate build script only targets UNIX systems and the `uplink` crate requires building the `uplink-sys`.

The [`uplink-sys` README](https://github.com/storj-thirdparty/uplink-rust/tree/main/uplink-sys#building-from-repo) mentions how to build in Linux and OSX, hence, I think that we should clarify it in the README that other platforms may not work and platforms that aren't of the UNIX family don't work.

There is a discussion about if we should include the compiled `uplink-c` library objects of several operative systems and not require Go to be installed for the most used Operative systems (Linux, OSX, and Windows). [In my comment](https://github.com/storj-thirdparty/uplink-rust/issues/19#issuecomment-1366802363), I mentioned that we should change the `build.rs` script of the `uplink-sys` crate to make it work.

I opened an [issue to track the `build.rs` enhancement](https://github.com/storj-thirdparty/uplink-rust/issues/61) and closed this one to favor it.

Thank you for your interest in this crate.
